name: Build, Test, and Deploy to Helm
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint || true
      - name: Build
        run: npm run build || true
      - name: Build Docker image
        run: docker build -t giggle-map-foundation:latest .
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0
      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: v1.29.0
      - name: Configure Kubeconfig
        run: echo "$KUBECONFIG_DATA" | base64 --decode > $HOME/.kube/config
        env:
          KUBECONFIG_DATA: ${{ secrets.KUBECONFIG_DATA }}
      - name: Deploy with Helm
        run: |
          helm upgrade --install giggle-map-api ./operations/api --namespace default --create-namespace

