name: Deploy to Helm
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0
      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: v1.29.0
      - name: Configure Kubeconfig
        run: echo "$KUBECONFIG_DATA" | base64 --decode > $HOME/.kube/config
        env:
          KUBECONFIG_DATA: ${{ secrets.KUBECONFIG_DATA }}
      - name: Deploy with Helm
        run: |
          helm upgrade --install giggle-map-api ./operations/api --namespace default --create-namespace

